CREATE TABLE Library.Authors (
AuthorId INT IDENTITY(1,1) PRIMARY KEY,
FirstName NVARCHAR(100) NOT NULL,
LastName NVARCHAR(100) NOT NULL,
BirthDate DATE NULL,
Country NVARCHAR(100) NULL,
CONSTRAINT UQ_Authors_FullName UNIQUE (FirstName, LastName)
);