CREATE TABLE Library.Returns (
ReturnId INT IDENTITY(1,1) PRIMARY KEY,
BorrowingId INT NOT NULL,
ReturnedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
Penalty DECIMAL(10,2) NOT NULL DEFAULT(0),
Notes NVARCHAR(4000) NULL,
CONSTRAINT FK_Returns_Borrowing FOREIGN KEY (BorrowingId) REFERENCES Library.Borrowings(BorrowingId)
);